global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.0.165:9090']

  - job_name: 'Machine'
    scrape_interval: 5s
    scrape_timeout: 2s
    static_configs:
      - targets: ['192.168.0.165:9100']

  - job_name: 'cAdvisor' 
    scrape_interval: 5s
    static_configs:
     - targets: ['192.168.0.165:8080']

  - job_name: "spring-actuator"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["192.168.0.165:3001","192.168.0.165:2000"]     
